---
title: "Thesis Weekly Log"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Week 1: 17 February - 23 February

#### This week's research and objectives
  Since this is week 1, I did not accomplish much in the terms of research. I spent time gathering resources and setting up this github repository. I've done some intial reading of the resources. I have gathered textbooks on sampling, surveys, and polls. Some areas I want to read further about is volunteer subject sampling, haphazard sampling, and quota sampling. 
  
#### Coming up
  With the next few weeks, I want to have completed a literature review on non-probability sampling. I need to set up an appointment with Robin Ford so that I can establish a relationship with them, and gain some insight on the best way to acquire literature in the sciences. Currently, all of my text resources have been published prior to 2000. I think it would be useful to find a more recently published resource to see how the methodolgy and opinions of sampling have changed.
